language: node_js
node_js:
- 0.10

notifications:
- joaopaulosis@hotmail.com

<<<<<<< HEAD
services:
- mongodb

env:
	global:
		- NODE_ENV: test

addons:
	sauce_connect: true
	
=======
>>>>>>> f78d4d92f5ace4b702c691c5508677cf181f9a26
before_install:
- npm install -g bower@1.3
- npm install -g grunt-cli@0.1
- npm install -g karma-cli@0.0
- npm install -g protractor@1.5
- webdriver-manager update
- bower install

before_script:
- grunt
- cd dist

script:
<<<<<<< HEAD
- karma start config/karma.config.js --single-run --browsers PhantomJS
- node server &
- protractor config/protractor.js
=======
- karma start config/karma.config.js --single-run --browsers PhantomJS
>>>>>>> f78d4d92f5ace4b702c691c5508677cf181f9a26
